segmentio/chamber

- LICENSE
- Makefile
- README.md
- circle.yml
- cmd/exec.go
- cmd/history.go
- cmd/list.go
- cmd/root.go
- cmd/write.go
- main.go
- store/ssmstore.go
- store/ssmstore_test.go
- store/store.go
> initial code:

- store/ssmstore.go
- There is an undocumented limit of 10 parameters per call
> batch calls to GetParameters:

- cmd/root.go
- store/ssmstore.go
- Will attempt to use the ec2 metadata API to look up current region
if AWS_REGION environment variable is not set
> try to determine region automatically if not set:

- Makefile
- README.md
- circle.yml
- vendor/vendor.json
Fix automatic github releasing
> Fix autorelease

- README.md
- store/ssmstore.go
Trying to help out with https://github.com/segmentio/chamber/issues/16, @ejcx let me know what you think about this
> add KMS info to readme and allow configuring via env var

- README.md
> README.md: Note about setting the AWS Region

- cmd/delete.go
- cmd/exec.go
- cmd/history.go
- cmd/list.go
- cmd/read.go
- cmd/root.go
- cmd/write.go
- vendor/vendor.json
Remove some code, easier to understand, better error message and usage
display.
Requires newer versions of:
* github.com/spf13/cobra
* github.com/pkg/errors
> Use standard cobra API for argument checking.

- README.md
- cmd/list.go
This is a tiny improvement to list secrets with values
> Implement persistent cmd flag to expand list output with values

- store/ssmstore.go
Previous code would still query EC2 metadata API if region is found in
~/.aws/config. This might make chamber run slow (10 secs delay on my
machine) on non-EC2 instances due to extra HTTP request to
169.254.169.254 which does not exist.
What is more, let AWS SDK read region from AWS_REGION environment
variable, do not attempt to do this manually.
> Do not query EC2 metadata API if region is in ~/.aws/config.

- cmd/write.go
After using `chamber` for some time I find that most of time I put single line secrets there. My other observation is that it becomes error prone (especially for new users) to remember about pressing `Ctrl+D` at the end of string.
That's why I propose to add `--singleline` option to save parameter just after hitting enter. 
Another use case for that is copying parameters between services:
```chamber read -q service1 parameter | chamber write -s service2 parameter -```
Without this feature, provided example adds trailing `\n` at the end of copied value.
> Add suport for --singleline option in write command

- cmd/export.go
> add support for exporting to an env file

- Makefile
- README.md
- cmd/import.go
- cmd/list.go
- cmd/root.go
- cmd/version.go
- main.go
- store/ssmstore.go
This is a breaking change and will come with a major version bump (v2.0)
> Use path based parameter store API by default

- cmd/write.go
By default a write attempt results in a new history entry even when the value is unchanged. Under most use this is no big deal but I've run into cases where we update secrets through automation, for example syncing during transitions between systems, and the history is filled with a bunch of non-changes. This adds a simple option to ignore writing the secret if the value is unchanged.
This is also easy to accomplish with a tiny bit of scripting but it has come up in a few different cases for me so I figure I would see if there is any interest in baking it in. Putting it in the tool does give the option to later push the implementation down into the store implementations if someone wanted to save a double read with the s3 backend, for example.
Thanks for looking!
> add write --skip-unchanged flag

- cmd/export.go
A popular use case for `chamber` is to use it to provide secrets to Terraform,
the format is fairly similar to `dotenv` but with stripping of `TF_VAR_` if present.
This last part ensures support for having a var `tf_var_this_that` be usable both as
`exec` and `export` or just have `this_that` and trim does nothing.
```
❯ awsve dev.admin -- chamber write testa tf_var_thisthat foobar   
❯ awsve dev.admin -- chamber write testa foo_bar barfoo 
❯ awsve dev.admin -- chamber list testa --         
Key                     Version         LastModified    User
foo_bar                 1               02-13 16:33:19  arn:aws:sts::123123:assumed-role/OrganizationAccountAccessRole/123123
tf_var_thisthat         1               02-13 16:32:55 …
```
> Add support to export as Terraform Variables

- .github/CODEOWNERS
- .github/stale.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
> style: add CONTRIBUTING and related stuff

- .circleci/config.yml
https://circleci.com/workflow-run/bf8308ac-2d79-44d0-8752-960a7c072bf7
First try 🆗 	
Ignore the failed Circle Enterprise jobs. I've disabled that webhook.
> pipelin: use circle contexts for publishing to github, packagecloud

- README.md
This [feature](https://github.com/segmentio/chamber/pull/188) needs some ❤️
> Update readme to include tfvars in export format

- cmd/write.go
> doc: `write ... -- value` works

- cmd/delete.go
- cmd/exec.go
- cmd/find.go
- cmd/find_test.go
- cmd/history.go
- cmd/import.go
- cmd/list.go
- cmd/read.go
- cmd/root.go
- cmd/write.go
- environ/environ.go
- environ/environ_test.go
- go.mod
- main.go
> fix: Switch to proper v2 tag

- README.md
This PR adds directions for setting env vars in your terminal
> docs: add directions for terminal env vars

- Makefile.release
> Sync supported debian/ubuntu releases

- README.md
Fix directions for setting env vars, close #259
> Fix directions for setting env vars, close #259

- cmd/root.go
- store/backendbenchmarks_test.go
- store/ssmstore.go
- store/ssmstore_test.go
> feat: Configure aws sdk min throttle delay using command argument

- Makefile.release
> Revert "Linux arm64 release fix for github and packagecloud"

- README.md
I was looking for a way to list all the services, and I found https://github.com/segmentio/chamber/issues/141 and https://github.com/segmentio/chamber/pull/187, but I noticed that the README doesn't mention the command.
> docs: Document the list-services command

- .github/workflows/build.yml
- .github/workflows/release.yml
- go.mod
[Jira ticket](https://segment.atlassian.net/browse/DEVEX-2052)
> chore: upgrade go to 1.22

- .github/workflows/build.yml
- .github/workflows/release.yml
- Dockerfile
Adds CI and release support for go1.24
Resolves #619
> build: go1.24
