- store/ssmstore.go
- store/ssmstore_test.go
Before this change, list could match services by prefix, which is pretty undesirable.  Includes a test so we don't regress
> List should match service exactly

- README.md
- cmd/exec.go
This adds a warning printed to stderr if you have conflicting secret names from loading secrets from multiple services.
It also clarifies this behavior in the readme for `exec`.  I'm not super happy with the copy there, so if you have suggestions for improving it let me know.
> Clarify conflicting secrets

- cmd/exec.go
Environment variables with dashes are generally not supported by most shells.  This replaces any dashes in the key name with underscores instead.
> replace dashes with underscores when exporting to the environment

- store/ssmstore.go
- store/ssmstore_test.go
- vendor/vendor.json
With the new AWS fix, we often encounter blank pages before the ones we were looking for, so use the paginator API instead
> sometime results have empty pages, account for that

- cmd/exec.go
- cmd/history.go
- cmd/list.go
- cmd/read.go
- cmd/root.go
- cmd/write.go
- vendor/vendor.json
After setting up chamber to wrap my app, I had some mysterious failures and found this in my logs:
```
ThrottlingException: Rate exceeded
status code: 400, request id: aacd7f1b-a7b6-11e7-9180-0708e1f58f4b
```
It took me a while to track down that that was coming from chamber rather than something within my application.
This change adds some decoration to the errors created by chamber to more clearly identify it as the source of the error message, as well as adding a bit more depth to the message to aid diagnosis.
A sample error now looks like this:
```
➜  ./chamber list dev
chamber error: Failed to list store contents: MissingRegion: could not find region configuration
```
> adding more descriptive errors

- .gitignore
- README.md
- cmd/write.go
If `-` is provided as the final argument to `chamber write`, read the
secret's value from standard input.  This is particularly useful when
the value consists of multiple lines (e.g., TLS certificate material).
> Accept data from standard input

- cmd/exec.go
- cmd/history.go
- cmd/list.go
- cmd/read.go
- cmd/root.go
- cmd/write.go
- store/ssmstore.go
we at honeycomb are running up against aws throttling DescribeParameter api calls (issue #34)
This diff adds a flag for max-retries (`--retries`/`-r`).  The default value is 10, which seems to fix things for 15 simultaneous runs of `while :; do chamber exec dev -- echo hi ; echo bye; done`.
The flag is attached to the `RootCmd`, so invoking it will look something like:
```
$ chamber --retries 100 exec something -- command
$ chamber -r 100 exec something -- command
```
`numRetries` is passed to all `store.NewSSMStore` calls, which doesn't feel very golang-like.  Maybe I should add a `store.StoreConfig` struct?  Let me know!
> add --retries/-r root flag and configure the SSM client to retry

- cmd/exec.go
Debugging something and noticed this. Figured I'd send a quick patch to fix =]
> exec: utilize `ErrCommandMissing`

- README.md
- cmd/list.go
- store/ssmstore.go
- store/ssmstore_test.go
This is a rough minimum edit change for using paths instead of dot separators.  If we go forward with this we should also:
- Update Describe and Get calls to use the Path options instead of string prefixing
- Bump to v2 as this is a breaking API change, probably put a notice in the readme as well
> use paths instead of '.' separating

- README.md
- store/ssmstore.go
Add a new env var `CHAMBER_AWS_REGION` which can be used to change chamber's region without interfering with the child application's region.
Fixes https://github.com/segmentio/chamber/issues/51
> Allow overriding region

- store/ssmstore.go
Similarly to https://github.com/segmentio/chamber/issues/34 and https://github.com/segmentio/chamber/pull/36 we ran into rate limiting problems when we started using chamber in production.
Retrying helped, but it does feel like it's a workaround. We wanted to see if we could find a better solution or get our rate limit raised, so we got in touch with AWS support and this is what they suggested.
`DescribeParameters` uses a default batch size of 10, but it can be increased up to 50. AWS support suggested make it 50.
We are currently running a forked version of chamber setting MaxResults to 50 and this seems to have made the problem go away. One of our apps has almost 60 secrets, this change reduced the number of calls to `DescribeParameters` from 6 to 2 (which is a significant change when …
> Increase DescribeParameters batch size from 10 to 50

- README.md
- cmd/delete.go
- cmd/exec.go
- cmd/export.go
- cmd/history.go
- cmd/list.go
- cmd/read.go
- cmd/root.go
- cmd/write.go
- vendor/vendor.json
It allows to export parameters in various formats. In this comment, the
following formats are supported:
* json
* java-properties (.properties)
* csv
* tsv
Depends on https://github.com/segmentio/chamber/pull/56 (though could be refactored not to depend on it)
>  Add export command

- store/ssmstore.go
Sometimes the SSM API returns nil descriptions, especially when the secret was created in parameter store outside of chamber.  Here we treat things with null descriptions as version 0 instead of panic'ing
> guard against null description pointers

- cmd/exec.go
- cmd/exec_default.go
- cmd/exec_unix.go
Fixes #37 
Seems like it works, I would take some advises on how to better test this:
```
$ aws-vault exec stage -- ./chamber exec service -- env
TERM_PROGRAM=iTerm.app
EDITOR_DEFAULT=subl
TERM=xterm-256color
SHELL=/bin/bash
...
```
(not sure what env var we're supposed to see getting set here, also I just learned by default editor is sublime... what a shame)
Here are the changes I made:
- move the fallback execution logic (copy/pasting) to `exec_default.go`
- add the execution based on syscall.Exec in `exec_unix.go` with build tags to use it on unix systems
- change the default execution logic to forward all signals from 1 to 31, so on platforms other than linux and darwin we do our best not to mask signals intended to the program ran by chamber.
Please let me know if anything should be …
> use syscall.Exec instead of exec.Command

- cmd/exec.go
- cmd/export.go
- store/ssmstore.go
- store/ssmstore_test.go
- store/store.go
Fix for: https://github.com/segmentio/chamber/issues/76
The SSM DescribeParameters API has very aggressive rate-limits because it's only meant for manual cli-usage. This can lead to significant delays or timeout errors when using chamber exec/export simultaneously in several places (eg. when starting a whole lot of processes in production).
Chamber uses the DescribeParameters API to find parameters by prefix (eg. 'myservice.*') when listing parameters. There's no better API for this in the general case, but if using paths, AWS provides a GetParametersByPath API which is designed for production usage and has much higher rate-limits. Unlike DescribeParameters, GetParametersByPath only returns parameter names and values; it does not include any metadata (eg. createdOn timestamps).
This PR …
> Avoid AWS rate-limits

- store/ssmstore.go
Read ~/.aws/config to load region configuration.
This will make chamber behave as documented in README.
Fixes #69
> sdk: load config by default

- README.md
`CHAMBER_NO_PATHS chamber` is not a valid way to set an environment variable in bourne-like shells.
> Fix example command in README

- README.md
- cmd/delete.go
- cmd/exec.go
- cmd/export.go
- cmd/history.go
- cmd/import.go
- cmd/list.go
- cmd/read.go
- cmd/root.go
- cmd/write.go
- store/backendbenchmarks_test.go
- store/s3store.go
- store/shared.go
- store/ssmstore.go
- vendor/vendor.json
This PR adds an experimental S3 backend.  We have run into some AWS rate limiting issues around using Parameter Store at scale, even when using the newer GetParameterByPaths API.  For some very high concurrency cases, we want to explore using S3 with server side encryption, and it would be nice if we could continue to use the same chamber interface.
For storage, the S3 backend assumes a single global secrets bucket by AWS account.  The object layout looks like:
```
chamber-secrets
└── service-foo
├── bar.json
├── baz.json
└── __latest.json
```
Where `service-foo` is a service with two secrets, `baz` and `bar`.
`__latest.json` is an index of sorts, which keeps the latest values of each secret for the service, but none of the metadata or previous versions.  This file is used by the …
> S3 backend

- store/ssmstore.go
- store/ssmstore_test.go
If there's no matching parameter, the api returns an empty list, in which case we return `ErrSecretNotFound`. Otherwise we should return the original error.
[Fixes #104]
> Return original error on reading parameter.

- Makefile
> Add chamber-$(VERSION).sha256sums generation

- cmd/exec.go
- cmd/root.go
It's useful to know the exact keys that are picked up by Chamber as that
information is not otherwise available anywhere else
> Print env var keys on exec with a global`-v` flag

- .circleci/config.yml
- .gitignore
- Makefile
- Makefile.release
- Makefile.tools
- nfpm.yaml.tmpl
- Build deb/rpm packages in `dist` job, using nfpm
- Split `Makefile` in to `Makefile` (simple; mostly aimed at users who want to build it themselves), `Makefile.release` (complex; aimed at CI/devs) and `Makefile.tools` (one-off installation tasks)
- Add `test` job/recipe
- Publish prerelease tags (e.g. `v2.1.0-anythingwithadash`) as github prereleases (mostly for testing this process)
- Publish binaries, packages, and sha256sum to a Github release
- Publish packages to PackageCloud
Ended up refactoring a lot of the Makefile and fixing circle in general. I had to use a fair few GNU Make tricks to get it to work in the end; maybe that's crazy
```
$ docker run -it -v `pwd`:/tmp debian sh
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 12 package 'chamber':
missing …
```
> Add deb/rpm packages

- Makefile
- README.md
- cmd/delete.go
- cmd/exec.go
- cmd/export.go
- cmd/history.go
- cmd/import.go
- cmd/list.go
- cmd/read.go
- cmd/root.go
- cmd/version.go
- cmd/write.go
- main.go
- vendor/vendor.json
This adds metrics to chamber so we can track internal company usage of the tool. Chamber built for open source will not have the linked analytics key.
This PR basically copies the way metrics were added to aws-okta
> Adding analytics for usage metrics

- README.md
- cmd/root.go
- store/nullstore.go
The addition of a `NULL` backend store, next to `s3` and `ssm`. Invoked by the ENV variable `CHAMBER_SECRET_BACKEND` set to `NULL`. The null-backend has no actual backend. Chamber will simply transparently pass through ENV vars.  https://github.com/segmentio/chamber/issues/143 is the related issue.
In some use cases the transformation into using Chamber inside an (external) organisation is not always straight forward. In many cases it is not only a migration on AWS from using ENV to using SSM/KMS, but also a migration from other providers like Heroku to AWS. To be able to get an organisation prepared with applications still sitting outside of AWS, with various teams and various docker orchestrations, it would be great to already have chamber implemented in a lazy way without the need to …
> Addition of a NULL Backend to provide a simple way of disabling backend lookups

- cmd/export.go
- cmd/export_test.go
Fixes dotenv export for variables with newlines and other special
characters.
Escape helper borrowed from https://github.com/joho/godotenv/blob/master/godotenv.go (MIT licensed).
> Quote environment variables.

- cmd/export.go
- store/ssmstore.go
Fix 2 typos detected by `misspell`:
```
cmd/export.go:72:76: "overriden" is a misspelling of "overridden"
store/ssmstore.go:382:46: "occured" is a misspelling of "occurred"
```
> Fix 2 typos

- cmd/list.go
This adds sorting options to the list command which is extremely useful in services with many secrets.
> added list sorting options

- README.md
The json in example for `export` command is not valid. Fix the example output.
> Fix typo in export example

- store/ssmstore.go
- store/ssmstore_test.go
Fixes issue #86 - because the `GetParameterHistory` API is limited to 50 results per request, secret versions greater than 50 did not show up in the history and could not be retrieved.
> Fix missing history and failed reads beyond secret version 50

- store/ssmstore.go
- store/ssmstore_test.go
At some point the SSM `GetParameterHistory` call started returning the current version in its response. (My guess is that this might have happened when AWS introduced official support for versioning, though I haven't confirmed that.) That turns the various old workarounds for the missing "current" version into bugs, like this:
```
$ chamber write myservice mysecret foo
$ chamber history myservice mysecret 
Event		Version		Date		User
Created		1		10-13 17:37:21	[redacted]
Created		1		10-13 17:37:21	[redacted]
$ chamber write myservice mysecret bar
$ chamber history myservice mysecret 
Event		Version		Date		User
Created		1		10-13 17:37:21	[redacted]
Updated		2		10-13 17:37:48	[redacted]
Updated		2		10-13 17:37:48	[redacted]
```
This PR fixes that. After the fix:
```
$ chamber write myservice …
```
> Remove extra history entry for the current parameter version

- README.md
Adding this example as an easier way for users to get started with chamber, since it won't require creating a key
> Adding an example of using the AWS default alias

- cmd/root.go
- go.mod
- go.sum
- store/backendbenchmarks_test.go
- store/s3store.go
Deprecate NewS3Store to avoid env var in lib
> add NewS3StoreWithBucket constructor

- cmd/exec.go
- environ/environ.go
I could have just copy-pasted this stuff, but there's a fair amount of fiddly details that I think could use capturing in their own exported library
This is for another docker entrypoint system that I'm working on that would work better if chamber weren't an extra binary.
> export environ as its own lib

- cmd/exec.go
This adds the `--pristine` flag to only use secretes retrieved from the backend when launching the child process. This prevents leaking the host's environment to the child process.
We're using [envconsul](https://github.com/hashicorp/envconsul) at Splice and we want to move to chamber instead so we're porting the `--pristine` flag from `envconsul`. I really wish this could be the default behviour but it would break existing usage.
I'm not sure how to add tests for this. I didn't see any tests for the `exec` command.
One thing to mention is that `--pristine` will also remove the variables added by tools like `aws-vault` making it harder for dev environments. 
```
$ aws-vault exec dev -- ./chamber list service       
Key		Version		LastModified	User
db_host		1		11-20 10:45:23 …
```
> Add `--pristine` to `exec` command

- go.mod
- go.sum
Picking up support for credential_source. This allows assuming a role
while using profile creds from ec2 instance metadata:
https://github.com/aws/aws-sdk-go/pull/2201.
> update AWS SDK to v1.15.90

- go.mod
- go.sum
- vendor/vendor.json
Update to the newest available AWS SDK which is v1.16.26. The main reason behind it is to add support for the `credential_process` in AWS SDK configuration.
This is the first time I've worked with go since the introduction of modules, so let me know if there's more to it than just bumping the version in `go.mod`
This resolves #180.
> Update AWS SDK to v1.16.26

- cmd/env.go
This resolves #94 by adding a new command that will print the secrets in a format that can be `eval`'ed to export them as environment variables.
> Add env command to export secrets

- README.md
- store/shared.go
- store/ssmstore_test.go
Based on https://github.com/segmentio/chamber/pull/49, allows for using
https://github.com/localstack/localstack with chamber. Localstack now
supports SSM.
> Allow to use a custom AWS SSM endpoint

- Dockerfile
- Makefile
- README.md
This doesn't build/publish automatically yet, but it's a start. Enables you to do
```
FROM segment/chamber:2 AS chamber
FROM scratch
COPY --from=chamber /chamber /bin/chamber
COPY ./myapp /bin/myapp
ENTRYPOINT ["/bin/chamber", "exec", "myapp", "--", "/bin/myapp"]
```
> Dockerfile

- README.md
- cmd/root.go
`--backend` takes an option that is either a bare backend name like `ssm` or a URL like `s3://<bucket>`. I can imagine a world where it could take query options like `ssm://?use-v1-paths=1` instead of passing those by yet another env var*
This also extends the current `CHAMBER_SECRET_BACKEND` to allow for the URL syntax as well.
Besides that one, this gets us away from the proliferation of gross env vars. IMO env vars are just a bad UX vs flags. For one, none of our env vars are documented in the online help, only the README. This flag is documented in `--help`.
* This would require detangling the scattering of env vars all over the lib code base. I started trying to do that, but not sure it's worth the effort https://github.com/segmentio/chamber/pull/183
> add global --backend flag

- Makefile.release
These 2 versions of Ubuntu are out and currently supported, though they are not LTS versions. I recently upgraded from Bionic (current LTS) through Cosmic and to Disco and the PPA for chamber stopped working as a result.
After this is merged, we should tag a new release.
> feat(packagecloud): add ubuntu/cosmic + ubuntu/disco releases

- cmd/root.go
Currently, the date format printed to STDOUT only includes the month and day. This change adds the year to the date format.
> update date format to include year

- cmd/list-services.go
- store/nullstore.go
- store/s3store.go
- store/s3storeKMS.go
- store/shared.go
- store/ssmstore.go
- store/store.go
This is a draft implementation of a search command.
In many cases we need to search for services and we have to fallback to `aws ssm` which is ok,
but it could be a good idea to implement this simple search functionality in `chamber`.
Let me know your thoughts and ill add the missing parts
Service name: `servicename`
```
❯ awsve dev.admin -- dist/chamber-v2.3.3-pre2-5-g059f1d1-dev-linux-amd64 search /servicena  
Service
/servicename/secreta
/servicename/secretb
```
> Add search command for SSM backend

- README.md
- cmd/find.go
- cmd/find_test.go
In response to https://github.com/segmentio/chamber/issues/221
This adds a `find` command to chamber which can be used to find similar Keys in a store.
```
$ chamber find -h
Find the given secret across all services
Usage:
chamber find <secret> [flags]
Flags:
-v, --by-value   Find parameters by value
-h, --help       help for find
```
```
$ chamber find s3_bucket_name
Service
service1
service2
service5
```
```
$ chamber find s3://this_bucket --by-value
Service				Key
service1			s3_bucket_name
service2			s3_bucket_name
service3			s3_bucket
service4			s3_bucket_base
service5			s3_bucket_name
```
> feat: Add `find` command

- .circleci/config.yml
- Dockerfile
- Makefile
- Makefile.release
E.g., for v2.3.1, publish :2.3.1 :2.3 :2
For v2.3.1-pre1, publish :prerelease-2.3.1-pre1 :prerelease-2.3 :prerelease-2
The prereleases like :prerelease-2 could be any old trash, but this helps us test the pipeline.
Also fixes dockerfile to use golang1.13
> pipeline: publish to docker hub

- store/s3storeKMS.go
I noticed that the `export` implementation uses `ListRaw` to iterate over the secrets in the store and return them in the requested format, while the `env` functionality uses `List`. `ListRaw` was not included in #195 which implements the S3-KMS backend, so the `env` command works correctly, but `export`, which is more flexible, does not. This PR rectifies this so that `export` will work correctly.
> fix: Implements ListRaw required for export from S3-KMS store

- README.md
**Context**
There is no section that explains the secret key normalization rule:
1. Uppercase
2. `-` will become `_`
It caused a lot of developers to debug this issue during developing an application unless they saw the source codes https://github.com/segmentio/chamber/blob/master/environ/environ.go#L82-L84
**Changes**
Added a section to explain that rules so developers will be aware of this rule before deploying their applications into production using chamber even without seeing the source codes
> docs: add secret key normalization rule

- cmd/exec.go
- cmd/list.go
- cmd/root.go
- cmd/root_test.go
- store/ssmstore.go
- store/ssmstore_test.go
Added support for SSMStore. Format: `/foo:v1`, `/foo` service, `v1` is the label. This is backwards compatible and does not break existing API.
> Label support for SSMStore

- cmd/root.go
- cmd/root_test.go
Fixes #245 by making the path/label optional in the regex.
Added test coverage of the specific scenario reported in #242
> fix: bad regex regression introduced by #242

- Makefile.release
Debian 10.0 (codename "buster") is the most recent stable release, and was released in July 2019. This PR adds a debian buster package to those hosted on packagecloud.io, which adds compatibility for those installing chamber via apt-get on buster-based virtual machines and images.
> Add debian/buster to packagecloud.io releases

- .dockerignore
- Dockerfile
- Makefile
- Makefile.release
This change adds a `.dockerignore` file to this repo that explicitly ignores `.git` and other, potentially sensitive directories. To keep the versioning logic (which depends on git) working in `docker build` steps, it passes the version in to docker instead of generating it during the image build process.
> Ignore .git in images

- .circleci/config.yml
we're switching tokens/users for doing releases. I've added the PAT as an env var in Circle.
> pipeline: remove release context

- store/secretsmanagerstore.go
Fix as suggested by error message
```
store/secretsmanagerstore.go:216:78: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL    github.com/segmentio/chamber/v2/store [build failed]
```
> Fix go 1.15 build

- store/s3storeKMS.go
We've started using `chamber exec` in some interactive CLI tools and noticed that it was quite slow in many cases. This is because the S3 KMS backend was making an unnecessary request for each secret, in addition to fetching all of the secrets in one go via the index file.
`ListRaw` was originally implented as a wrapper for `List` in https://github.com/segmentio/chamber/pull/236. This is unnecessarily slow, since `ListRaw` doesn't need any of the additional info about each secret provided by `List`. Now, `ListRaw` doesn't call `List`; instead, it just pulls the data it needs straight from the index file.
This reduces a typical chamber invocation for one of our services from 3 seconds to 0.65 seconds.
This change marginally increases the chance of something going wrong if the index file …
> Optimise ListRaw for S3-KMS backend

- Makefile
- Makefile.release
I need to run chamber on some AWS Graviton instances so adding the support to release a arm64 binary.
> Add support for linux/arm64

- Makefile.release
This is a fix for PR https://github.com/segmentio/chamber/pull/307 so that we can release linux arm64 chamber to github as well as an arm64 debian to packagecloud
> Linux arm64 release fix for github and packagecloud

- README.md
Using the Copy button that Github renders on the code snippets in README.md, ie.
the content copied to the clipboard is `$ go get github.com/segmentio/chamber`.
Pasting this content won't work because it's prefixed with the `$` character.
In this PR, I'm removing all the `$` characters from the copiable code snippets so that the Copy button copies the right content.
> Fix copiable code snippets in README.md

- .circleci/config.yml
Replaced the personal token from my account with the service account given by IT. "Documenting" it by adding this comment to the .circle file. Feel free to suggest I add it elsewhere. 
https://segment.atlassian.net/browse/TOOL-2071
> Added comment to our .circle file explaining where the GH_LOGIN env variable secret is stored

- store/ssmstore.go
Before this change I measured list-services taking 4m8.79s on stage, afterwards it took 1m18.70s. I don't think these numbers are super accurate because of Parameter Store's low rate limits and retries, but I think this will improve `list-services` performance.
> improve `list-services` performance by increasing page size

- README.md
This PR is adding clarification to the readme about aws-vault and that it's not the only way. (Some twilio/segment users were experiencing confusion looking at the docs thinking we used aws-vault here.)
> DEVPLAT-440 language clairfication update

- Makefile.release
There was a publish-github-arm64-deb target under publish-github which no longer exists, and publish-github-linux-arm64 exists but isn't in PHONY. Cleaning that up, as I'd love to have a linux/arm64 package of chamber if there's a release sometime soon for use on graviton instances!
> Cleanup from merges/reverts of arm64 targets

- .github/workflows/build.yml
- .github/workflows/release.yml
The [PR merge](https://github.com/segmentio/chamber/pull/335) we made created an error when publishing to github. We decided to move away from the `github-release` step in the Makefile and use Github actions steps instead to publish to github. Since this is automated and more streamlined that what the Makefile is doing. Through this, we also decided to use the automated CHANGELOG generation provided by Github Actions.
Here is the error for the PR that was merged: https://github.com/segmentio/chamber/actions/runs/2116343973
> Automate release process using a github action module

- .github/CODEOWNERS
- CONTRIBUTING.md
* sets `.github/CODEOWNERS` to a valid definition
* cleans up `CONTRIBUTING` file to fix invalid anchor link and lint the file
> docs: update CODEOWNERS and cleanup contributing guide

- Dockerfile
This fixes the below error when using chamber in docker: `docker run segment/chamber:2.10.8 list-services ...`
```
Error: Failed to list store contents: RequestError: send request failed
caused by: Post "https://ssm.us-east-1.amazonaws.com/": x509: certificate signed by unknown authority
```
> fix x509: certificate signed by unknown authority error when using docker

- cmd/root.go
- cmd/root_test.go
enhance error message to clarify validity of forward slashes in service names
Resolves #333
> fix: enhance error message to clarify validity of forward slashes in service names

- .github/workflows/build.yml
- README.md
- go.mod
- go.sum
> chore: installation for Go 1.18

- .github/workflows/build.yml
Removes `test-dockerhub-login` from feature branch pipeline because secrets aren't accessible from forked repositories. It should only only be executed during release(once PR is merged) pipeline when publishing to Docker Registry.
> Remove test-dockerhub-login step from feature branches pipelines

- go.mod
- go.sum
update yaml package to v3.0.1 to resolve vulnerabilities
> fix: update yaml package to resolve vulnerabilities

- Dockerfile
We recently got pinged about a security vulnerability: https://github.com/segmentio/chamber/issues/367
This PR aims to fix that by updating the golang version in the Dockerfile to `1.19`
> fix: update golang version to 1.19 in dockerfile

- README.md
- cmd/delete.go
- cmd/env.go
- cmd/export.go
- cmd/history.go
- cmd/import.go
- cmd/list-services.go
- cmd/list.go
- cmd/read.go
- cmd/write.go
- environ/environ.go
- utils/utils.go
- utils/utils_test.go
Mitigates #160, #324, #369
Adds two forward-thinking options in lieu of implementing breaking change behavior.
* minor refactor to move some shared code logic/expectations to a `utils` package
* `chamber import`
* added the `--normalize-keys` flag
* `chamber delete`
* added the `--preserve-key` flag
The first two commits are just minor refactors. It is recommended to review by each commit to reduce styling/refactor noise.
Please excuse my Prettier running rampant on `README.md`
> feat: add options for import and delete normalization handling

- go.mod
- go.sum
- Resolve `AWS_PROFILE` with `aws sso` issues
- Closes https://github.com/segmentio/chamber/issues/376
Before update
```bash
✗ AWS_PROFILE=test chamber list-services
Error: Failed to get secret store: SharedConfigErr: only one credential type may be specified per profile: source profile, credential source, credential process, web identity token, or sso
```
```bash
✗ go get -u github.com/aws/aws-sdk-go@v1.38
```
~Replace was necessary in order to run `go get -u`~
```bash
✗ go mod edit -replace gopkg.in/segmentio/analytics-go.v3=github.com/segmentio/analytics-go/v3@v3.2.1
✗ go mod tidy
```
After update
```bash
✗ rm -f chamber && make build
✗ AWS_PROFILE=test ./chamber list-services
Service
hello-world/secret
```
> chore(deps): resolve aws sso profile issues by updating aws-sdk-go@v1.38

- .github/workflows/build.yml
- .github/workflows/release.yml
- go.mod
Bumps the minimum go version for `chamber` to be go 1.16. This aligns with our current test and distributables support.
> feat: bump minimum go version

- cmd/delete.go
- cmd/env.go
- cmd/exec.go
- cmd/exec_default.go
- cmd/exec_unix.go
- cmd/export.go
- cmd/find.go
- cmd/find_test.go
- cmd/history.go
- cmd/import.go
- cmd/list-services.go
- cmd/list.go
- cmd/read.go
- cmd/root.go
- cmd/version.go
- cmd/write.go
- environ/environ.go
- go.mod
- go.sum
- main.go
- store/s3storeKMS.go
- utils/utils.go
So, `chamber` has accumulated a number of papercuts over the years: small things, easy to overlook but that sting in the moment. Nothing that's going to completely halt operation, but will annoy you (read: me, Joe Sportsbar Average User) when you touch them. Here's a swing at fixing a few of these up in the hopes of further improving future maintenance: 
- Improve test readability for `cmd/find_test.go`
- Use contemporary `go:build` directives format instead of deprecated `+build:`
- Remove legacy 3rd party error wrapping package and use contemporary stdlib error wrapping
> Fix accumulated papercuts

- cmd/env.go
- cmd/env_test.go
- cmd/export.go
- cmd/export_test.go
- go.mod
- go.sum
This was reported in https://github.com/segmentio/chamber/issues/366: `chamber` made no effort to sanitize keys for either of these commands or formats, which can result in invalid variable names being used for both of these output formats. This PR fixes half of the problem (invalid characters in retrieved keys when rendered via `env` or `export -f dotenv`) but does not address the larger question of "what is a valid character when writing a key?"
Some of the construction of these formats have now been unified, with an optional boolean flag for `env` to preserve key case -- note that keys will still be sanitized, they just won't be converted to uppercase. Since `export -f dotenv` rewrites values using escape characters, I've made the choice to continue allowing `export -f dotenv` to …
> Fix `chamber env` and `chamber export -f dotenv`

- README.md
Adds information about which versions of Go we will test against and support, which version of Go we will build distributable executables with, caveats about `chamber env` and `chamber export -o dotenv`, and general formatting tweaks to make `markdownlint` yell at me a little less while I was in here.
> Update `README` for pending 2.13.0 release

- Dockerfile
This is due to CVE-2023-39323 and fixes #428
> chore: update docker build to use golang 1.20.9

- .github/workflows/build.yml
- .github/workflows/release.yml
- Dockerfile
- go.mod
- go.sum
Also update go.mod version and dependencies to latest versions.
> .github: update to Go 1.21

- Dockerfile
Bump golang from 1.21.2 to 1.21.4 to address CVE-2023-45283:
> Bump golang from 1.21.2 to 1.21.4 to address CVE-2023-45283

- Dockerfile
The vulnerability in CVE-2023-45285 could allow for dependencies to be pulled insecurely. This upgrades the go version used in the docker build to prevent that.
> Bump docker golang from 1.21.4 to 1.21.5 to address CVE-2023-45285

- .github/dependabot.yml
This will help ensure that the golang version used in the docker container is kept up to date.
Closes https://github.com/segmentio/chamber/issues/442
> Add docker updates to dependabot config

- .github/workflows/build.yml
- .github/workflows/release.yml
We're seeing some consistent 400 responses in our `dist` steps for our GitHub actions. After doing some digging, it looks like the [v4 version of the Artifacts GitHub Actions](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/) was made available in early December that should resolve and/or make more reliable these actions.
The `v4` versions of these actions come with some breaking changes and requirements that are addressed in this PR:
* If we are using `actions/upload-artifacts@v4`, we _**must also**_ be using `actions/download-artifacts@v4`
* Artifact uploads **must** contain unique names.
> ci: bump actions/upload-artifact and actions/download-artifact to v4

- CONTRIBUTING.md
- README.md
To make it clear that third-party contributions are given under the MIT
license.
Also, there's a bit of info in the readme about the name "chamber".
> docs: Add licensing verbiage to CONTRIBUTING.md

- .gitignore
- Makefile
Running fmt becomes a prerequisite for building chamber, helping to keep
the code formatted.
The coverage target runs basic code coverage tests, and sets the stage
for reporting.
> build: Add fmt and coverage make targets

- README.md
- cmd/root.go
- store/s3store.go
- store/s3storeKMS.go
- store/secretsmanagerstore.go
- store/secretsmanagerstore_test.go
- store/shared.go
- store/shared_test.go
- store/ssmstore.go
- store/ssmstore_test.go
The v2 AWS SDK has no equivalent setting for a minimum delay for
throttle errors. So, the delay has been replaced with the new retry mode
configuration setting that is available. The "adaptive" mode accounts
for throttle errors, although it is not configurable any further than
that, and the mode itself is still experimental.
The choice of retry mode still only applies to the SSM parameter store,
but it could be extended to other implementations very easily.
The `--min-throttle-delay` option remains in place so that existing
scripted calls don't break, but the value no longer has any effect.
The README is updated accordingly, mentioning the loss of min throttle
delay as a breaking change. The removal of the `CHAMBER_NO_PATHS`
avoiding of the path-based API for the SSM parameter store is …
> feat!: Switch from min throttle delay to retry mode

- cmd/exec.go
- cmd/find.go
- cmd/list.go
- cmd/root.go
- cmd/root_test.go
- environ/environ.go
- environ/environ_test.go
- store/ssmstore.go
- store/ssmstore_test.go
Version 2.0 of chamber deprecated use of the non-path-based API for the
SSM parameter store. This commit removes support for it completely.
Since the deprecation occurred so long ago, this changeset does not
preserve the ability to migrate to using the path-based API. Migration
may be performed with a 2.x version of chamber prior to upgrading to
a 3.x version.
BREAKING CHANGE: Any users or clients still using the non-path-based SSM API will see errors working with the SSM parameter store.
> chore!: Remove deprecated support for non-path SSM API

- cmd/delete.go
- cmd/env.go
- cmd/exec.go
- cmd/export.go
- cmd/find.go
- cmd/history.go
- cmd/import.go
- cmd/list-services.go
- cmd/list.go
- cmd/read.go
- cmd/root.go
- cmd/write.go
- environ/environ.go
- store/backendbenchmarks_test.go
- store/nullstore.go
- store/s3store.go
- store/s3storeKMS.go
- store/secretsmanagerstore.go
- store/secretsmanagerstore_test.go
- store/shared.go
- store/shared_test.go
- store/ssmstore.go
- store/ssmstore_test.go
- store/store.go
The new AWS SDK uses contexts for all API functions and for loading the
SDK configuration. When chamber was migrated to the SDK, all of them
were set to `context.TODO()`. This commit removes those temporary values
and threads contexts properly throughout the codebase, starting from the
chamber commands.
BREAKING CHANGE: This commit changes the signature of many exported
functions to add a context argument.
> refactor!: Properly support contexts

- Makefile
- cmd/delete.go
- cmd/env.go
- cmd/env_test.go
- cmd/exec.go
- cmd/export.go
- cmd/history.go
- cmd/import.go
- cmd/list.go
- cmd/read.go
- cmd/root.go
- cmd/version.go
- cmd/write.go
- environ/environ.go
- store/backendbenchmarks_test.go
- store/s3store.go
- store/s3storeKMS.go
- store/secretsmanagerstore.go
- store/secretsmanagerstore_test.go
- store/shared_test.go
- store/ssmstore.go
- store/ssmstore_test.go
The new `make lint` target runs golangci-lint if installed locally. It
is not (yet) required for a passing build.
Most issues reported by golangci-lint are resolved. Some interesting
ones:
* Missing error checking is added for exporting to a properties file and
to Terraform variables.
* Unused functions are removed: stringInSlice, S3KMSStore.readObject.
* Unused variables are removed: validKeyFormat.
* Write operations used to set up store tests now have their errors
checked. If a setup write fails, the test immediately fails.
Unresolved issues:
* Use of EndpointResolverWithOptions
* Missing error checks for flushing, syncing, and closing a file
created by the export command
> chore: Add golangci-lint and fix most issues

- Makefile
Why be implicit when you can be explicit?
> Use an explicit default make target/goal

- cmd/root.go
- cmd/root_test.go
- cmd/tag-delete.go
- cmd/tag-read.go
- cmd/tag-write.go
- cmd/tag.go
- store/awsapi.go
- store/awsapi_mock.go
- store/nullstore.go
- store/s3store.go
- store/secretsmanagerstore.go
- store/ssmstore.go
- store/ssmstore_test.go
- store/store.go
The new commands are for reading, writing, and deleting tags on the
underlying resources representing secrets.
For now, the commands are only implemented for SSM parameters.
> feat: Add tag read, write, and delete commands

- store/secretsmanagerstore.go
- store/secretsmanagerstore_test.go
- store/shared.go
- store/shared_test.go
- store/ssmstore.go
- store/ssmstore_test.go
The v2 AWS SDK introduces a new endpoint resolution mechanism where
custom endpoints are specified on a per-service basis, while the
previous global mechanism is deprecated. This changeset switches to the
newer mechanism.
The default resolver under the new mechanism uses the base endpoint in
a service client's `Options` as the means to customize endpoints, so
it's enough for tests to make sure the base endpoint gets set.
Under the previous mechanism, the CHAMBER_AWS_SSM_ENDPOINT environment
variable was used to customize not just the endpoint for SSM, but also
for Secrets Manager. This changeset deprecates the latter use in favor
of a new CHAMBER_AWS_SECRETS_MANAGER_ENDPOINT environment variable.
There seems to also be SDK-native ways to use the environment for
endpoint customization, so …
> refactor: Switch to AWS endpoint resolution v2

- README.md
- cmd/write.go
- store/nullstore.go
- store/s3store.go
- store/s3storeKMS.go
- store/secretsmanagerstore.go
- store/ssmstore.go
- store/ssmstore_test.go
- store/store.go
Store implementations may support tagging secrets immediately after they
are created, as a convenience and a basis for future enforcement of
tagging. As usual, only the SSM store implementation supports the new
feature.
The README is updated with documentation about both this new feature and
the recently added tag commands.
> feat: Add tag-on-create

- README.md
#267  added secret manager support, so I updated the readme to note that. That way people won't need to dig through the issues to figure out what the support status is.
I've checked "allow edits by maintainers", so feel free to change the wording / formatting :)
> add note about secrets manager

- cmd/env.go
- cmd/env_test.go
Despite the github.com/joho/godotenv implementation which originated
dotenv support here, neither github.com/bkeepers/dotenv (Ruby) nor
github.com/motdotla/dotenv (Node) escape exclamation points in the
format. See https://github.com/segmentio/chamber/issues/485 for
research.
Fixes #485
> fix: Do not escape exclamation points when exporting to dotenv

- README.md
- cmd/root.go
- cmd/root_test.go
- store/store.go
- store/store_test.go
The service may still be used normally, but doing so emits warnings. A
future chamber version should prohibit using it entirely.
> feat: Reserve _chamber service

- store/nullstore.go
- store/s3store.go
- store/secretsmanagerstore.go
- store/secretsmanagerstore_test.go
- store/ssmstore.go
- store/ssmstore_test.go
- store/store.go
The new Config and SetConfig methods on the Store interface allow
implementations to maintain their own configurations. Only the SSM store
fully implements the methods; the others return an empty configuration
and do not support setting one.
The store configuration itself holds a list of required tags for each
written secret. Enforcement of the tags is not yet implemented. Although
the configuration struct is exported from its package, it is not part of
chamber's client interface and is subject to change at any time.
The SSM store implementation stores its configuration as a secret
inside the newly reserved "_chamber" service as a JSON document. The
schema is not exported, so users shouldn't build anything from it.
> feat!: Add store configuration support for SSM store

- store/shared.go
When running on an EC2 instance with an instance profile / role, chamber
now finds the region correctly.
> fix: Find region correctly from EC2 IMDS

- store/ssmstore.go
- store/ssmstore_test.go
- store/store.go
The behavior is as follows:
* When writing a new secret, all required tags must be provided.
* When writing tags to a secret, and other tags are being deleted, then all required tags that are already present on the secret must be provided.
* When deleting tags from a secret, required tags may not be provided.
The second item is a bit subtle. If other tags aren't being deleted, i.e., tags not provided are being left alone, then required tags don't have to be provided (they may be, but don't have to be). Also, if other tags *are* being deleted, then the only required tags that have to be provided are those that are already set. These behaviors are designed so that after a store's configuration is updated to require tags, you don't have to then immediately set them all on every existing …
> feat: Enforce required tags in SSM store

- .github/dependabot.yml
Group Dependabot PRs for `aws-sdk-go-v2` into a single grouped pull request
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
With the swap to `aws-sdk-go-v2`, each AWS SDK dependency is treated as a unique package and opens a new PR
This is extremely noisy and expensive for GitHub actions usage.
> ci(dependabot): group aws-sdk-go-v2 updates into a single pr

- cmd/exec.go
- cmd/root.go
The small amount of verbose logging in the exec command has been
converted to debug logging under log/slog.
> chore: Convert to log/slog
